# Generated by Django 3.0.5 on 2020-06-24 08:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BrokerUI', '0007_auto_20200624_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vmodel', models.CharField(max_length=50)),
                ('make', models.CharField(max_length=20)),
                ('desc', models.TextField()),
                ('age', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('year', models.IntegerField()),
                ('fueltank', models.CharField(choices=[('P', 'PETROL'), ('D', 'DIESEL'), ('C', 'CNG')], max_length=1)),
                ('price', models.IntegerField(blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrokerUI.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='VehiclePred',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predprice', models.IntegerField()),
                ('actualprice', models.IntegerField()),
                ('vehicleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SellerUI.Vehicle')),
            ],
        ),
    ]
