# Generated by Django 3.0.4 on 2020-04-14 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SellerUI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vmodel', models.CharField(max_length=50)),
                ('make', models.CharField(max_length=20)),
                ('desc', models.TextField()),
                ('age', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('year', models.IntegerField()),
                ('fueltank', models.CharField(choices=[('P', 'PETROL'), ('D', 'DIESEL'), ('C', 'CNG')], max_length=1)),
                ('price', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleListed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sellerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SellerUI.SellerProfile')),
                ('vehicleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SellerUI.Vehicle')),
            ],
        ),
    ]
