# Generated by Django 3.0.5 on 2020-06-25 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SellerUI', '0002_auto_20200625_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiclepredprice',
            old_name='make',
            new_name='Make',
        ),
        migrations.RenameField(
            model_name='vehiclepredprice',
            old_name='model',
            new_name='Model',
        ),
        migrations.RenameField(
            model_name='vehiclepredprice',
            old_name='type',
            new_name='Type',
        ),
        migrations.RenameField(
            model_name='vehiclepredprice',
            old_name='year',
            new_name='Year',
        ),
    ]
