# Generated by Django 3.0.5 on 2020-06-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellerUI', '0003_auto_20200625_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='photo',
            field=models.ImageField(blank=True, upload_to='vehicle_images'),
        ),
    ]
