# Generated by Django 3.0.5 on 2020-06-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellerUI', '0004_vehicle_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='photo',
            field=models.ImageField(blank=True, upload_to='vehicle_image'),
        ),
    ]
