# Generated by Django 3.0.6 on 2020-05-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrokerUI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokerprofile',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
