# Generated by Django 3.0.5 on 2020-05-28 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BrokerUI', '0002_auto_20200527_2340'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BrokerProfile',
        ),
    ]
