# Generated by Django 3.0.5 on 2020-06-04 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BrokerUI', '0003_delete_brokerprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('U', 'User'), ('S', 'Seller'), ('B', 'Broker')], default='none', max_length=1)),
                ('phone_number', models.CharField(max_length=5)),
                ('is_user', models.BooleanField(default=False)),
                ('is_seller', models.BooleanField(default=False)),
                ('is_broker', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('price', models.FloatField()),
                ('bedroom', models.PositiveIntegerField()),
                ('bathroom', models.PositiveIntegerField()),
                ('carpetarea', models.IntegerField()),
                ('builtuparea', models.IntegerField()),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrokerUI.Profile')),
            ],
        ),
    ]
