# Generated by Django 3.0.5 on 2020-06-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrokerUI', '0005_prediction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='bathrooms',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)]),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='rooms',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)]),
        ),
    ]
