# Generated by Django 3.0.5 on 2020-06-24 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrokerUI', '0006_auto_20200604_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_broker',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_seller',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_user',
        ),
        migrations.AlterField(
            model_name='prediction',
            name='project',
            field=models.CharField(choices=[('Pavilion Heights: PR/GJ/VADODARA/VADODARA/Others/RAA05921/210819', 'Pavilion Heights'), ('Devesh Imperia', 'Devesh Imperia'), ('White lotus', 'White lotus'), ('PRAKRUTI', 'PRAKRUTI'), ('STATUS', 'STATUS'), ('Ananta swagatam', 'Ananta swagatam'), ('Saakar belleza', 'Saakar belleza'), ('SAMRUDDHI', 'SAMRUDDHI'), ('VIHAV SKYONE: PR/GJ/VADODARA/VADODARA/Others/MAA03997/061118', 'VIHAV SKYONE'), ('Gotbull', 'Gotbull'), ('PARAM BLISS', 'PARAM BLISS'), ('Anant park society', 'Anant park society'), ('NAMAN HEIGHTS', 'NAMAN HEIGHTS'), ('PARAM CREST', 'PARAM CREST'), ('Dwarkesh Avenue', 'Dwarkesh Avenue'), ('Girikunj Apartment', 'Girikunj Apartment'), ('GOLDEN VALLEY', 'GOLDEN VALLEY'), ('GUNATIT RESIDENCY', 'GUNATIT RESIDENCY'), ('SHYAMAL COUNTY- TYPE-B', 'SHYAMAL COUNTY'), ('PARAM CREST-PR/GJ/VADODARA/VADODARA/Others/MAA05269/120419', 'PARAM CREST')], max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('S', 'Seller'), ('C', 'Customer'), ('B', 'Broker')], max_length=1),
        ),
    ]
