# Generated by Django 3.0.5 on 2020-06-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrokerUI', '0007_auto_20200624_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='construction_status',
            field=models.CharField(choices=[('under_construction', 'under_construction'), ('launched', 'launched'), ('ready_to_move', 'ready to move')], default="can't say", max_length=50),
        ),
        migrations.AddField(
            model_name='estate',
            name='furnished',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no'), ('semi', 'semi')], default="can't say", max_length=10),
        ),
        migrations.AddField(
            model_name='estate',
            name='project',
            field=models.CharField(default="can't say", max_length=400),
        ),
        migrations.AddField(
            model_name='estate',
            name='sublocality',
            field=models.CharField(default="can't say", max_length=100),
        ),
        migrations.AddField(
            model_name='estate',
            name='type',
            field=models.CharField(choices=[('apartments', 'apartments'), ('sale-floors', 'sale-floors'), ('houses', 'houses')], default="can't say", max_length=100),
        ),
    ]
