# Generated by Django 3.0.5 on 2020-06-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrokerUI', '0008_auto_20200625_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='profile_pics'),
        ),
    ]
