# Generated by Django 3.0.5 on 2020-06-26 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BrokerUI', '0009_profile_profile_image'),
        ('SellerUI', '0006_vehicle_bought'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiclesBought',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrokerUI.Profile')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SellerUI.Vehicle')),
            ],
        ),
    ]
